In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [5]:
data=np.random.randint(-2,20,(4,2))
data

array([[ 7, 10],
       [14,  1],
       [10,  5],
       [-1, 19]])

In [6]:
scaler=MinMaxScaler()
new_data=scaler.fit_transform(data)
new_data

array([[0.53333333, 0.5       ],
       [1.        , 0.        ],
       [0.73333333, 0.22222222],
       [0.        , 1.        ]])

In [9]:
scaler.inverse_transform(new_data).astype(int)

array([[ 7, 10],
       [14,  1],
       [10,  5],
       [-1, 19]])

In [16]:
data=pd.read_csv('/Users/hurrywish/Downloads/Python_sklearn/【第01部分 核心教程】sklearn深度学习框架入门与实战 3套/02.2019年Scikit-learn的机器学习入门到精通（附讲义、代码、数据集、参考资料） 258课/00.配套资料（代码、讲义、数据等）/00.配套资料（代码、讲义、数据等）/03数据预处理和特征工程/Narrativedata.csv',index_col=0)
data.columns


Index(['Age', 'Sex', 'Embarked', 'Survived'], dtype='object')

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [25]:
from sklearn.impute import SimpleImputer

SI=SimpleImputer(missing_values=np.nan,strategy='median')
age_data=SI.fit_transform(np.array(data['Age']).reshape(-1,1))
age_data
data1=data.copy()
data1['Age']=age_data
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


## 手写识别

In [27]:
data=pd.read_csv('/Users/hurrywish/Downloads/Python_sklearn/【第01部分 核心教程】sklearn深度学习框架入门与实战 3套/02.2019年Scikit-learn的机器学习入门到精通（附讲义、代码、数据集、参考资料） 258课/00.配套资料（代码、讲义、数据等）/00.配套资料（代码、讲义、数据等）/03数据预处理和特征工程/digit recognizor.csv')

In [28]:
data.head(10)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   
5       0  ...         0         0         0         0         0         0   
6       0  ...         0         0         0         0         0         0   
7       0  ...         0         0         0         0         0         0   
8       0  ...         0         0         0         0         0         0   
9       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  
5         0         0         0         0  
6         0         0         0         0  
7         0         0         0         0  
8         0         0         0         0  
9         0         0         0         0  

[10 rows x 785 columns]

In [29]:
sample=data[data.columns[1:]]
target=data[data.columns[0]]

In [30]:
sample.shape,target.shape

((42000, 784), (42000,))

In [42]:
from sklearn.feature_selection import VarianceThreshold
var_median=np.median(sample.var().values)
VT=VarianceThreshold(var_median)
x_var0=VT.fit_transform(sample)
x_var0.shape

(42000, 392)

In [39]:
var_median=np.median(sample.var().values)

1352.286703180131

In [11]:
from sklearn.feature_selection import f_classif,VarianceThreshold,SelectFromModel,RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

data=pd.read_csv('/Users/hurrywish/Downloads/Python_sklearn/【第01部分 核心教程】sklearn深度学习框架入门与实战 3套/02.2019年Scikit-learn的机器学习入门到精通（附讲义、代码、数据集、参考资料） 258课/00.配套资料（代码、讲义、数据等）/00.配套资料（代码、讲义、数据等）/03数据预处理和特征工程/digit recognizor.csv')


sample=data[data.columns[1:]]
label=data[data.columns[0]]

clfs=dict()
clfs['DTC']=DecisionTreeClassifier(random_state=1)
clfs['RFC']=RandomForestClassifier(random_state=1,n_jobs=-1)
#clfs['KNC']=KNeighborsClassifier(n_jobs=-1)

samples=dict()

samples['sample_0']=sample
samples['samples_median_V']=VarianceThreshold(np.median(sample.var().values)).fit_transform(sample)
samples['samples_mean_V']=VarianceThreshold(np.mean(sample.var().values)).fit_transform(sample)
samples['samples_mean_Emb']=SelectFromModel(RandomForestClassifier(),threshold=0.005).fit_transform(sample,label)
samples['samples_RFE']=RFE(estimator=RFC,n_features_to_select=340,step=50).fit_transform(sample,label)

for i in clfs:
    clf=clfs[i]
    for j in samples:
        vals=samples[j]
        score_cross=cross_val_score(clf,vals,label,cv=5).mean()
        print('clf:',i)
        print('sample:',j)
        print('score:',score_cross)


clf: DTC
sample: sample_0
score: 0.856452380952381
clf: DTC
sample: samples_median_V
score: 0.8547142857142858
clf: DTC
sample: samples_mean_V
score: 0.8516904761904762
clf: DTC
sample: samples_mean_Emb
score: 0.8045476190476191
clf: DTC
sample: samples_RFE
score: 0.8536904761904761
clf: RFC
sample: sample_0
score: 0.9639523809523809
clf: RFC
sample: samples_median_V
score: 0.9641666666666667
clf: RFC
sample: samples_mean_V
score: 0.9635714285714286
clf: RFC
sample: samples_mean_Emb
score: 0.9038333333333334
clf: RFC
sample: samples_RFE
score: 0.9643095238095238


In [64]:
from sklearn.feature_selection import f_classif,VarianceThreshold
F,P=f_classif(sample,label)

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [  0   1   2   3   4   5   6   7   8   9  10  11  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  52  53  54  55  56  57  82  83
  84  85 111 112 139 140 141 168 196 392 420 421 448 476 532 560 644 645
 671 672 673 699 700 701 727 728 729 730 731 754 755 756 757 758 759 760
 780 781 782 783] are constant.
  UserWarning)
/Users/hurrywish/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


array([            nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
       4.39099677e-001, 5.21661528e-001, 4.32226198e-001, 4.32226198e-001,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
       4.23355793e-001, 2.03324046e-001, 1.13655921e-004, 4.70215339e-008,
       7.91901538e-013, 3.59228937e-022, 1.64909033e-043, 2.97856228e-063,
       1.73557975e-073, 1.65904031e-068, 4.60813314e-056, 1.53764296e-047,
       1.56761187e-042, 6.08944380e-044, 2.36206175e-039, 2.17970772e-021,
       1.10353465e-015, 4.44886362e-005, 1.67573602e-003, 3.08710900e-001,
                   nan,  

In [65]:
from sklearn.feature_selection import mutual_info_classif

result=mutual_info_classif(sample,target)
result

array([4.05955144e-03, 0.00000000e+00, 3.74740931e-03, 0.00000000e+00,
       1.18650000e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.54927851e-03, 0.00000000e+00, 4.19123434e-03,
       3.28474860e-03, 1.36329143e-03, 4.09604193e-04, 0.00000000e+00,
       0.00000000e+00, 1.71616925e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.49205761e-04, 1.89758850e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.04349803e-04, 2.11652885e-03, 5.14958812e-03, 4.49072166e-03,
       5.50268710e-03, 0.00000000e+00, 2.37023507e-03, 1.97066088e-03,
       9.95550952e-03, 1.73352020e-03, 6.93353250e-03, 1.58583443e-03,
       1.20725187e-03, 0.00000000e+00, 0.00000000e+00, 3.56458691e-03,
       5.06108053e-05, 1.16309948e-03, 0.00000000e+00, 6.55684846e-04,
       0.00000000e+00, 0.00000000e+00, 7.91368292e-05, 3.88468209e-03,
      

In [88]:
sample=data[data.columns[1:]]
label=data[data.columns[0]]

RFC=RandomForestClassifier(n_jobs=-1)
RFC.fit(sample,label)
high_limit=max(RFC.feature_importances_)
threshold_range=np.linspace(0,high_limit,50)

scores=list()
for i in threshold_range:
    sample_emb=SelectFromModel(RFC,threshold=i).fit_transform(sample,label)
    score=cross_val_score(RFC,sample,label,cv=5).mean()
    scores.append(score)

print(scores)
plt.plot(threshold_range,scores)

KeyboardInterrupt: 

## 包装法

In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [7]:
data=pd.read_csv('/Users/hurrywish/Downloads/Python_sklearn/【第01部分 核心教程】sklearn深度学习框架入门与实战 3套/02.2019年Scikit-learn的机器学习入门到精通（附讲义、代码、数据集、参考资料） 258课/00.配套资料（代码、讲义、数据等）/00.配套资料（代码、讲义、数据等）/03数据预处理和特征工程/digit recognizor.csv')
sample=data[data.columns[1:]]
label=data[data.columns[0]]
RFC=RandomForestClassifier(n_estimators=10,n_jobs=-1)
selector=RFE(estimator=RFC,n_features_to_select=340,step=50).fit(sample,label)
selector.ranking_

array([10,  9,  8,  7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  7,  7,  7,  6,  7,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  5,  5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  6,  5,  3,  3,
        4,  3,  3,  4,  5,  4,  3,  6,  6,  6,  5,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  5,  5,  5,  3,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  2,  2,  3,  4,  8,  8,  8,  9,  9,  9,  9,  9,  8,  7,  6,  5,
        4,  3,  3,  2,  1,  1,  1,  1,  1,  1,  1,  2,  1,  2,  3,  3,  4,
        5,  5,  9, 10, 10, 10, 10, 10,  5,  4,  4,  2,  3,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  3,  9,  8, 10, 10, 10,
        9,  8,  5,  4,  3,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  2,  3,  4,  8, 10, 10, 10, 10,  6,  4,  3,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        4,  7, 10,  9,  9

## 包装法